In [23]:
# Dependencies
from bs4 import BeautifulSoup as bs
import requests
import json
from flask import Flask, render_template, redirect
from sqlalchemy import create_engine
from sqlalchemy import Column, Integer, String, Float

from sqlalchemy.ext.declarative import declarative_base
from pprint import pprint
import pandas as pd
Base = declarative_base()

In [33]:
url="https://datausa.io/api/data?drilldowns=State&measures=Population"

In [34]:
# Performing a GET request similar to the one we executed
# earlier
response = requests.get(url)
print(response.url)

https://datausa.io/api/data?drilldowns=State&measures=Population.json

In [39]:
url = "http://www.omdbapi.com/?t="
api_key = "&apikey=trilogy"
response = requests.get(url + "The Great Wall" + api_key)
print(response.url)

http://www.omdbapi.com/?t=The%20Great%20Wall&apikey=trilogy

### Tried to extract data from URL, but it was forbidden. So the data was copied and pasted into population.txt

In [37]:
# Converting the response to JSON, and printing the result.
data = response.json()
print(data)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [57]:
pprint(data)

{'data': [{'ID State': '04000US39',
           'ID Year': 2018,
           'Population': 11689442,
           'Slug State': 'ohio',
           'State': 'Ohio',
           'Year': '2018'},
          {'ID State': '04000US72',
           'ID Year': 2018,
           'Population': 3195153,
           'Slug State': 'puerto-rico',
           'State': 'Puerto Rico',
           'Year': '2018'},
          {'ID State': '04000US01',
           'ID Year': 2018,
           'Population': 4887871,
           'Slug State': 'alabama',
           'State': 'Alabama',
           'Year': '2018'},
          {'ID State': '04000US55',
           'ID Year': 2018,
           'Population': 5813568,
           'Slug State': 'wisconsin',
           'State': 'Wisconsin',
           'Year': '2018'},
          {'ID State': '04000US02',
           'ID Year': 2018,
           'Population': 737438,
           'Slug State': 'alaska',
           'State': 'Alaska',
           'Year': '2018'},
          {'ID State': '04000US54',
           'ID Year': 2018,
           'Population': 1805832,
           'Slug State': 'west-virginia',
           'State': 'West Virginia',
           'Year': '2018'},
          {'ID State': '04000US53',
           'ID Year': 2018,
           'Population': 7535591,
           'Slug State': 'washington',
           'State': 'Washington',
           'Year': '2018'},
          {'ID State': '04000US04',
           'ID Year': 2018,
           'Population': 7171646,
           'Slug State': 'arizona',
           'State': 'Arizona',
           'Year': '2018'},
          {'ID State': '04000US51',
           'ID Year': 2018,
           'Population': 8517685,
           'Slug State': 'virginia',
           'State': 'Virginia',
           'Year': '2018'},
          {'ID State': '04000US05',
           'ID Year': 2018,
           'Population': 3013825,
           'Slug State': 'arkansas',
           'State': 'Arkansas',
           'Year': '2018'},
          {'ID State': '04000US50',
           'ID Year': 2018,
           'Population': 626299,
           'Slug State': 'vermont',
           'State': 'Vermont',
           'Year': '2018'},
          {'ID State': '04000US49',
           'ID Year': 2018,
           'Population': 3161105,
           'Slug State': 'utah',
           'State': 'Utah',
           'Year': '2018'},
          {'ID State': '04000US06',
           'ID Year': 2018,
           'Population': 39557045,
           'Slug State': 'california',
           'State': 'California',
           'Year': '2018'},
          {'ID State': '04000US48',
           'ID Year': 2018,
           'Population': 28701845,
           'Slug State': 'texas',
           'State': 'Texas',
           'Year': '2018'},
          {'ID State': '04000US08',
           'ID Year': 2018,
           'Population': 5695564,
           'Slug State': 'colorado',
           'State': 'Colorado',
           'Year': '2018'},
          {'ID State': '04000US47',
           'ID Year': 2018,
           'Population': 6770010,
           'Slug State': 'tennessee',
           'State': 'Tennessee',
           'Year': '2018'},
          {'ID State': '04000US46',
           'ID Year': 2018,
           'Population': 882235,
           'Slug State': 'south-dakota',
           'State': 'South Dakota',
           'Year': '2018'},
          {'ID State': '04000US09',
           'ID Year': 2018,
           'Population': 3572665,
           'Slug State': 'connecticut',
           'State': 'Connecticut',
           'Year': '2018'},
          {'ID State': '04000US45',
           'ID Year': 2018,
           'Population': 5084127,
           'Slug State': 'south-carolina',
           'State': 'South Carolina',
           'Year': '2018'},
          {'ID State': '04000US10',
           'ID Year': 2018,
           'Population': 967171,
           'Slug State': 'delaware',
           'State': 'Delaware',
           'Year': '2018'},
          {'ID State': '04000US44',
           'ID Year': 2018,
           'Population': 1057315,
           'Slug State': 'rhode-island',
           'State': 'Rhode Island',
           'Year': '2018'},
          {'ID State': '04000US42',
           'ID Year': 2018,
           'Population': 12807060,
           'Slug State': 'pennsylvania',
           'State': 'Pennsylvania',
           'Year': '2018'},
          {'ID State': '04000US11',
           'ID Year': 2018,
           'Population': 702455,
           'Slug State': 'district-of-columbia',
           'State': 'District of Columbia',
           'Year': '2018'},
          {'ID State': '04000US41',
           'ID Year': 2018,
           'Population': 4190713,
           'Slug State': 'oregon',
           'State': 'Oregon',
           'Year': '2018'},
          {'ID State': '04000US12',
           'ID Year': 2018,
           'Population': 21299325,
           'Slug State': 'florida',
           'State': 'Florida',
           'Year': '2018'},
          {'ID State': '04000US40',
           'ID Year': 2018,
           'Population': 3943079,
           'Slug State': 'oklahoma',
           'State': 'Oklahoma',
           'Year': '2018'},
          {'ID State': '04000US56',
           'ID Year': 2018,
           'Population': 577737,
           'Slug State': 'wyoming',
           'State': 'Wyoming',
           'Year': '2018'},
          {'ID State': '04000US13',
           'ID Year': 2018,
           'Population': 10519475,
           'Slug State': 'georgia',
           'State': 'Georgia',
           'Year': '2018'},
          {'ID State': '04000US38',
           'ID Year': 2018,
           'Population': 760077,
           'Slug State': 'north-dakota',
           'State': 'North Dakota',
           'Year': '2018'},
          {'ID State': '04000US15',
           'ID Year': 2018,
           'Population': 1420491,
           'Slug State': 'hawaii',
           'State': 'Hawaii',
           'Year': '2018'},
          {'ID State': '04000US37',
           'ID Year': 2018,
           'Population': 10383620,
           'Slug State': 'north-carolina',
           'State': 'North Carolina',
           'Year': '2018'},
          {'ID State': '04000US36',
           'ID Year': 2018,
           'Population': 19542209,
           'Slug State': 'new-york',
           'State': 'New York',
           'Year': '2018'},
          {'ID State': '04000US16',
           'ID Year': 2018,
           'Population': 1754208,
           'Slug State': 'idaho',
           'State': 'Idaho',
           'Year': '2018'},
          {'ID State': '04000US35',
           'ID Year': 2018,
           'Population': 2095428,
           'Slug State': 'new-mexico',
           'State': 'New Mexico',
           'Year': '2018'},
          {'ID State': '04000US17',
           'ID Year': 2018,
           'Population': 12741080,
           'Slug State': 'illinois',
           'State': 'Illinois',
           'Year': '2018'},
          {'ID State': '04000US34',
           'ID Year': 2018,
           'Population': 8908520,
           'Slug State': 'new-jersey',
           'State': 'New Jersey',
           'Year': '2018'},
          {'ID State': '04000US33',
           'ID Year': 2018,
           'Population': 1356458,
           'Slug State': 'new-hampshire',
           'State': 'New Hampshire',
           'Year': '2018'},
          {'ID State': '04000US18',
           'ID Year': 2018,
           'Population': 6691878,
           'Slug State': 'indiana',
           'State': 'Indiana',
           'Year': '2018'},
          {'ID State': '04000US32',
           'ID Year': 2018,
           'Population': 3034392,
           'Slug State': 'nevada',
           'State': 'Nevada',
           'Year': '2018'},
          {'ID State': '04000US19',
           'ID Year': 2018,
           'Population': 3156145,
           'Slug State': 'iowa',
           'State': 'Iowa',
           'Year': '2018'},
          {'ID State': '04000US31',
           'ID Year': 2018,
           'Population': 1929268,
           'Slug State': 'nebraska',
           'State': 'Nebraska',
           'Year': '2018'},
          {'ID State': '04000US30',
           'ID Year': 2018,
           'Population': 1062305,
           'Slug State': 'montana',
           'State': 'Montana',
           'Year': '2018'},
          {'ID State': '04000US20',
           'ID Year': 2018,
           'Population': 2911510,
           'Slug State': 'kansas',
           'State': 'Kansas',
           'Year': '2018'},
          {'ID State': '04000US29',
           'ID Year': 2018,
           'Population': 6126452,
           'Slug State': 'missouri',
           'State': 'Missouri',
           'Year': '2018'},
          {'ID State': '04000US21',
           'ID Year': 2018,
           'Population': 4468402,
           'Slug State': 'kentucky',
           'State': 'Kentucky',
           'Year': '2018'},
          {'ID State': '04000US28',
           'ID Year': 2018,
           'Population': 2986530,
           'Slug State': 'mississippi',
           'State': 'Mississippi',
           'Year': '2018'},
          {'ID State': '04000US27',
           'ID Year': 2018,
           'Population': 5611179,
           'Slug State': 'minnesota',
           'State': 'Minnesota',
           'Year': '2018'},
          {'ID State': '04000US22',
           'ID Year': 2018,
           'Population': 4659978,
           'Slug State': 'louisiana',
           'State': 'Louisiana',
           'Year': '2018'},
          {'ID State': '04000US26',
           'ID Year': 2018,
           'Population': 9995915,
           'Slug State': 'michigan',
           'State': 'Michigan',
           'Year': '2018'},
          {'ID State': '04000US23',
           'ID Year': 2018,
           'Population': 1338404,
           'Slug State': 'maine',
           'State': 'Maine',
           'Year': '2018'},
          {'ID State': '04000US25',
           'ID Year': 2018,
           'Population': 6902149,
           'Slug State': 'massachusetts',
           'State': 'Massachusetts',
           'Year': '2018'},
          {'ID State': '04000US24',
           'ID Year': 2018,
           'Population': 6042718,
           'Slug State': 'maryland',
           'State': 'Maryland',
           'Year': '2018'},
          {'ID State': '04000US04',
           'ID Year': 2017,
           'Population': 7016270,
           'Slug State': 'arizona',
           'State': 'Arizona',
           'Year': '2017'},
          {'ID State': '04000US13',
           'ID Year': 2017,
           'Population': 10429379,
           'Slug State': 'georgia',
           'State': 'Georgia',
           'Year': '2017'},
          {'ID State': '04000US48',
           'ID Year': 2017,
           'Population': 28304596,
           'Slug State': 'texas',
           'State': 'Texas',
           'Year': '2017'},
          {'ID State': '04000US39',
           'ID Year': 2017,
           'Population': 11658609,
           'Slug State': 'ohio',
           'State': 'Ohio',
           'Year': '2017'},
          {'ID State': '04000US08',
           'ID Year': 2017,
           'Population': 5607154,
           'Slug State': 'colorado',
           'State': 'Colorado',
           'Year': '2017'},
          {'ID State': '04000US38',
           'ID Year': 2017,
           'Population': 755393,
           'Slug State': 'north-dakota',
           'State': 'North Dakota',
           'Year': '2017'},
          {'ID State': '04000US15',
           'ID Year': 2017,
           'Population': 1427538,
           'Slug State': 'hawaii',
           'State': 'Hawaii',
           'Year': '2017'},
          {'ID State': '04000US55',
           'ID Year': 2017,
           'Population': 5795483,
           'Slug State': 'wisconsin',
           'State': 'Wisconsin',
           'Year': '2017'},
          {'ID State': '04000US53',
           'ID Year': 2017,
           'Population': 7405743,
           'Slug State': 'washington',
           'State': 'Washington',
           'Year': '2017'},
          {'ID State': '04000US37',
           'ID Year': 2017,
           'Population': 10273419,
           'Slug State': 'north-carolina',
           'State': 'North Carolina',
           'Year': '2017'},
          {'ID State': '04000US47',
           'ID Year': 2017,
           'Population': 6715984,
           'Slug State': 'tennessee',
           'State': 'Tennessee',
           'Year': '2017'},
          {'ID State': '04000US16',
           'ID Year': 2017,
           'Population': 1716943,
           'Slug State': 'idaho',
           'State': 'Idaho',
           'Year': '2017'},
          {'ID State': '04000US02',
           'ID Year': 2017,
           'Population': 739795,
           'Slug State': 'alaska',
           'State': 'Alaska',
           'Year': '2017'},
          {'ID State': '04000US36',
           'ID Year': 2017,
           'Population': 19849399,
           'Slug State': 'new-york',
           'State': 'New York',
           'Year': '2017'},
          {'ID State': '04000US09',
           'ID Year': 2017,
           'Population': 3588184,
           'Slug State': 'connecticut',
           'State': 'Connecticut',
           'Year': '2017'},
          {'ID State': '04000US35',
           'ID Year': 2017,
           'Population': 2088070,
           'Slug State': 'new-mexico',
           'State': 'New Mexico',
           'Year': '2017'},
          {'ID State': '04000US17',
           'ID Year': 2017,
           'Population': 12802023,
           'Slug State': 'illinois',
           'State': 'Illinois',
           'Year': '2017'},
          {'ID State': '04000US51',
           'ID Year': 2017,
           'Population': 8470020,
           'Slug State': 'virginia',
           'State': 'Virginia',
           'Year': '2017'},
          {'ID State': '04000US46',
           'ID Year': 2017,
           'Population': 869666,
           'Slug State': 'south-dakota',
           'State': 'South Dakota',
           'Year': '2017'},
          {'ID State': '04000US34',
           'ID Year': 2017,
           'Population': 9005644,
           'Slug State': 'new-jersey',
           'State': 'New Jersey',
           'Year': '2017'},
          {'ID State': '04000US05',
           'ID Year': 2017,
           'Population': 3004279,
           'Slug State': 'arkansas',
           'State': 'Arkansas',
           'Year': '2017'},
          {'ID State': '04000US18',
           'ID Year': 2017,
           'Population': 6666818,
           'Slug State': 'indiana',
           'State': 'Indiana',
           'Year': '2017'},
          {'ID State': '04000US45',
           'ID Year': 2017,
           'Population': 5024369,
           'Slug State': 'south-carolina',
           'State': 'South Carolina',
           'Year': '2017'},
          {'ID State': '04000US33',
           'ID Year': 2017,
           'Population': 1342795,
           'Slug State': 'new-hampshire',
           'State': 'New Hampshire',
           'Year': '2017'},
          {'ID State': '04000US10',
           'ID Year': 2017,
           'Population': 961939,
           'Slug State': 'delaware',
           'State': 'Delaware',
           'Year': '2017'},
          {'ID State': '04000US32',
           'ID Year': 2017,
           'Population': 2998039,
           'Slug State': 'nevada',
           'State': 'Nevada',
           'Year': '2017'},
          {'ID State': '04000US19',
           'ID Year': 2017,
           'Population': 3145711,
           'Slug State': 'iowa',
           'State': 'Iowa',
           'Year': '2017'},
          {'ID State': '04000US72',
           'ID Year': 2017,
           'Population': 3337177,
           'Slug State': 'puerto-rico',
           'State': 'Puerto Rico',
           'Year': '2017'},
          {'ID State': '04000US56',
           'ID Year': 2017,
           'Population': 579315,
           'Slug State': 'wyoming',
           'State': 'Wyoming',
           'Year': '2017'},
          {'ID State': '04000US31',
           'ID Year': 2017,
           'Population': 1920076,
           'Slug State': 'nebraska',
           'State': 'Nebraska',
           'Year': '2017'},
          {'ID State': '04000US44',
           'ID Year': 2017,
           'Population': 1059639,
           'Slug State': 'rhode-island',
           'State': 'Rhode Island',
           'Year': '2017'},
          {'ID State': '04000US20',
           'ID Year': 2017,
           'Population': 2913123,
           'Slug State': 'kansas',
           'State': 'Kansas',
           'Year': '2017'},
          {'ID State': '04000US50',
           'ID Year': 2017,
           'Population': 623657,
           'Slug State': 'vermont',
           'State': 'Vermont',
           'Year': '2017'},
          {'ID State': '04000US30',
           'ID Year': 2017,
           'Population': 1050493,
           'Slug State': 'montana',
           'State': 'Montana',
           'Year': '2017'},
          {'ID State': '04000US11',
           'ID Year': 2017,
           'Population': 693972,
           'Slug State': 'district-of-columbia',
           'State': 'District of Columbia',
           'Year': '2017'},
          {'ID State': '04000US29',
           'ID Year': 2017,
           'Population': 6113532,
           'Slug State': 'missouri',
           'State': 'Missouri',
           'Year': '2017'},
          {'ID State': '04000US21',
           'ID Year': 2017,
           'Population': 4454189,
           'Slug State': 'kentucky',
           'State': 'Kentucky',
           'Year': '2017'},
          {'ID State': '04000US54',
           'ID Year': 2017,
           'Population': 1815857,
           'Slug State': 'west-virginia',
           'State': 'West Virginia',
           'Year': '2017'},
          {'ID State': '04000US42',
           'ID Year': 2017,
           'Population': 12805537,
           'Slug State': 'pennsylvania',
           'State': 'Pennsylvania',
           'Year': '2017'},
          {'ID State': '04000US28',
           'ID Year': 2017,
           'Population': 2984100,
           'Slug State': 'mississippi',
           'State': 'Mississippi',
           'Year': '2017'},
          {'ID State': '04000US06',
           'ID Year': 2017,
           'Population': 39536653,
           'Slug State': 'california',
           'State': 'California',
           'Year': '2017'},
          {'ID State': '04000US22',
           'ID Year': 2017,
           'Population': 4684333,
           'Slug State': 'louisiana',
           'State': 'Louisiana',
           'Year': '2017'},
          {'ID State': '04000US41',
           'ID Year': 2017,
           'Population': 4142776,
           'Slug State': 'oregon',
           'State': 'Oregon',
           'Year': '2017'},
          {'ID State': '04000US27',
           'ID Year': 2017,
           'Population': 5576606,
           'Slug State': 'minnesota',
           'State': 'Minnesota',
           'Year': '2017'},
          {'ID State': '04000US12',
           'ID Year': 2017,
           'Population': 20984400,
           'Slug State': 'florida',
           'State': 'Florida',
           'Year': '2017'},
          {'ID State': '04000US26',
           'ID Year': 2017,
           'Population': 9962311,
           'Slug State': 'michigan',
           'State': 'Michigan',
           'Year': '2017'},
          {'ID State': '04000US23',
           'ID Year': 2017,
           'Population': 1335907,
           'Slug State': 'maine',
           'State': 'Maine',
           'Year': '2017'},
          {'ID State': '04000US01',
           'ID Year': 2017,
           'Population': 4874747,
           'Slug State': 'alabama',
           'State': 'Alabama',
           'Year': '2017'},
          {'ID State': '04000US49',
           'ID Year': 2017,
           'Population': 3101833,
           'Slug State': 'utah',
           'State': 'Utah',
           'Year': '2017'},
          {'ID State': '04000US25',
           'ID Year': 2017,
           'Population': 6859819,
           'Slug State': 'massachusetts',

          {'ID State': '04000US44',
           'ID Year': 2016,
           'Population': 1056426,
           'Slug State': 'rhode-island',
           'State': 'Rhode Island',
           'Year': '2016'},
          {'ID State': '04000US09',
           'ID Year': 2016,
           'Population': 3576452,
           'Slug State': 'connecticut',
           'State': 'Connecticut',
           'Year': '2016'},
          {'ID State': '04000US45',
           'ID Year': 2016,
           'Population': 4961119,
           'Slug State': 'south-carolina',
           'State': 'South Carolina',
           'Year': '2016'},
          {'ID State': '04000US10',
           'ID Year': 2016,
           'Population': 952065,
           'Slug State': 'delaware',
           'State': 'Delaware',
           'Year': '2016'},
          {'ID State': '04000US46',
           'ID Year': 2016,
           'Population': 865454,
           'Slug State': 'south-dakota',
           'State': 'South Dakota',
           'Year': '2016'},
          {'ID State': '04000US21',
           'ID Year': 2015,
           'Population': 4425092,
           'Slug State': 'kentucky',
           'State': 'Kentucky',
           'Year': '2015'},
          {'ID State': '04000US35',
           'ID Year': 2015,
           'Population': 2085109,
           'Slug State': 'new-mexico',
           'State': 'New Mexico',
           'Year': '2015'},
          {'ID State': '04000US01',
           'ID Year': 2015,
           'Population': 4858979,
           'Slug State': 'alabama',
           'State': 'Alabama',
           'Year': '2015'},
          {'ID State': '04000US72',
           'ID Year': 2015,
           'Population': 3474182,
           'Slug State': 'puerto-rico',
           'State': 'Puerto Rico',
           'Year': '2015'},
          {'ID State': '04000US17',
           'ID Year': 2015,
           'Population': 12859995,
           'Slug State': 'illinois',
           'State': 'Illinois',
           'Year': '2015'},
          {'ID State': '04000US30',
           'ID Year': 2015,
           'Population': 1032949,
           'Slug State': 'montana',
           'State': 'Montana',
           'Year': '2015'},
          {'ID State': '04000US36',
           'ID Year': 2015,
           'Population': 19795791,
           'Slug State': 'new-york',
           'State': 'New York',
           'Year': '2015'},
          {'ID State': '04000US26',
           'ID Year': 2015,
           'Population': 9922576,
           'Slug State': 'michigan',
           'State': 'Michigan',
           'Year': '2015'},
          {'ID State': '04000US51',
           'ID Year': 2015,
           'Population': 8382993,
           'Slug State': 'virginia',
           'State': 'Virginia',
           'Year': '2015'},
          {'ID State': '04000US55',
           'ID Year': 2015,
           'Population': 5771337,
           'Slug State': 'wisconsin',
           'State': 'Wisconsin',
           'Year': '2015'},
          {'ID State': '04000US06',
           'ID Year': 2015,
           'Population': 39144818,
           'Slug State': 'california',
           'State': 'California',
           'Year': '2015'},
          {'ID State': '04000US37',
           'ID Year': 2015,
           'Population': 10042802,
           'Slug State': 'north-carolina',
           'State': 'North Carolina',
           'Year': '2015'},
          {'ID State': '04000US40',
           'ID Year': 2015,
           'Population': 3911338,
           'Slug State': 'oklahoma',
           'State': 'Oklahoma',
           'Year': '2015'},
          {'ID State': '04000US16',
           'ID Year': 2015,
           'Population': 1654930,
           'Slug State': 'idaho',
           'State': 'Idaho',
           'Year': '2015'},
          {'ID State': '04000US04',
           'ID Year': 2015,
           'Population': 6828065,
           'Slug State': 'arizona',
           'State': 'Arizona',
           'Year': '2015'},
          {'ID State': '04000US50',
           'ID Year': 2015,
           'Population': 626042,
           'Slug State': 'vermont',
           'State': 'Vermont',
           'Year': '2015'},
          {'ID State': '04000US38',
           'ID Year': 2015,
           'Population': 756928,
           'Slug State': 'north-dakota',
           'State': 'North Dakota',
           'Year': '2015'},
          {'ID State': '04000US31',
           'ID Year': 2015,
           'Population': 1896190,
           'Slug State': 'nebraska',
           'State': 'Nebraska',
           'Year': '2015'},
          {'ID State': '04000US56',
           'ID Year': 2015,
           'Population': 586107,
           'Slug State': 'wyoming',
           'State': 'Wyoming',
           'Year': '2015'},
          {'ID State': '04000US15',
           'ID Year': 2015,
           'Population': 1431603,
           'Slug State': 'hawaii',
           'State': 'Hawaii',
           'Year': '2015'},
          {'ID State': '04000US20',
           'ID Year': 2015,
           'Population': 2911641,
           'Slug State': 'kansas',
           'State': 'Kansas',
           'Year': '2015'},
          {'ID State': '04000US39',
           'ID Year': 2015,
           'Population': 11613423,
           'Slug State': 'ohio',
           'State': 'Ohio',
           'Year': '2015'},
          {'ID State': '04000US28',
           'ID Year': 2015,
           'Population': 2992333,
           'Slug State': 'mississippi',
           'State': 'Mississippi',
           'Year': '2015'},
          {'ID State': '04000US54',
           'ID Year': 2015,
           'Population': 1844128,
           'Slug State': 'west-virginia',
           'State': 'West Virginia',
           'Year': '2015'},
          {'ID State': '04000US32',
           'ID Year': 2015,
           'Population': 2890845,
           'Slug State': 'nevada',
           'State': 'Nevada',
           'Year': '2015'},
          {'ID State': '04000US49',
           'ID Year': 2015,
           'Population': 2995919,
           'Slug State': 'utah',
           'State': 'Utah',
           'Year': '2015'},
          {'ID State': '04000US08',
           'ID Year': 2015,
           'Population': 5456574,
           'Slug State': 'colorado',
           'State': 'Colorado',
           'Year': '2015'},
          {'ID State': '04000US24',
           'ID Year': 2015,
           'Population': 6006401,
           'Slug State': 'maryland',
           'State': 'Maryland',
           'Year': '2015'},
          {'ID State': '04000US13',
           'ID Year': 2015,
           'Population': 10214860,
           'Slug State': 'georgia',
           'State': 'Georgia',
           'Year': '2015'},
          {'ID State': '04000US22',
           'ID Year': 2015,
           'Population': 4670724,
           'Slug State': 'louisiana',
           'State': 'Louisiana',
           'Year': '2015'},
          {'ID State': '04000US19',
           'ID Year': 2015,
           'Population': 3123899,
           'Slug State': 'iowa',
           'State': 'Iowa',
           'Year': '2015'},
          {'ID State': '04000US41',
           'ID Year': 2015,
           'Population': 4028977,
           'Slug State': 'oregon',
           'State': 'Oregon',
           'Year': '2015'},
          {'ID State': '04000US02',
           'ID Year': 2015,
           'Population': 738432,
           'Slug State': 'alaska',
           'State': 'Alaska',
           'Year': '2015'},
          {'ID State': '04000US33',
           'ID Year': 2015,
           'Population': 1330608,
           'Slug State': 'new-hampshire',
           'State': 'New Hampshire',
           'Year': '2015'},
          {'ID State': '04000US12',
           'ID Year': 2015,
           'Population': 20271272,
           'Slug State': 'florida',
           'State': 'Florida',
           'Year': '2015'},
          {'ID State': '04000US48',
           'ID Year': 2015,
           'Population': 27469114,
           'Slug State': 'texas',
           'State': 'Texas',
           'Year': '2015'},
          {'ID State': '04000US42',
           'ID Year': 2015,
           'Population': 12802503,
           'Slug State': 'pennsylvania',
           'State': 'Pennsylvania',
           'Year': '2015'},
          {'ID State': '04000US23',
           'ID Year': 2015,
           'Population': 1329328,
           'Slug State': 'maine',
           'State': 'Maine',
           'Year': '2015'},
          {'ID State': '04000US09',
           'ID Year': 2015,
           'Population': 3590886,
           'Slug State': 'connecticut',
           'State': 'Connecticut',
           'Year': '2015'},
          {'ID State': '04000US29',
           'ID Year': 2015,
           'Population': 6083672,
           'Slug State': 'missouri',
           'State': 'Missouri',
           'Year': '2015'},
          {'ID State': '04000US25',
           'ID Year': 2015,
           'Population': 6794422,
           'Slug State': 'massachusetts',
           'State': 'Massachusetts',
           'Year': '2015'},
          {'ID State': '04000US44',
           'ID Year': 2015,
           'Population': 1056298,
           'Slug State': 'rhode-island',
           'State': 'Rhode Island',
           'Year': '2015'},
          {'ID State': '04000US53',
           'ID Year': 2015,
           'Population': 7170351,
           'Slug State': 'washington',
           'State': 'Washington',
           'Year': '2015'},
          {'ID State': '04000US11',
           'ID Year': 2015,
           'Population': 672228,
           'Slug State': 'district-of-columbia',
           'State': 'District of Columbia',
           'Year': '2015'},
          {'ID State': '04000US47',
           'ID Year': 2015,
           'Population': 6600299,
           'Slug State': 'tennessee',
           'State': 'Tennessee',
           'Year': '2015'},
          {'ID State': '04000US34',
           'ID Year': 2015,
           'Population': 8958013,
           'Slug State': 'new-jersey',
           'State': 'New Jersey',
           'Year': '2015'},
          {'ID State': '04000US45',
           'ID Year': 2015,
           'Population': 4896146,
           'Slug State': 'south-carolina',
           'State': 'South Carolina',
           'Year': '2015'},
          {'ID State': '04000US27',
           'ID Year': 2015,
           'Population': 5489594,
           'Slug State': 'minnesota',
           'State': 'Minnesota',
           'Year': '2015'},
          {'ID State': '04000US18',
           'ID Year': 2015,
           'Population': 6619680,
           'Slug State': 'indiana',
           'State': 'Indiana',
           'Year': '2015'},
          {'ID State': '04000US10',
           'ID Year': 2015,
           'Population': 945934,
           'Slug State': 'delaware',
           'State': 'Delaware',
           'Year': '2015'},
          {'ID State': '04000US05',
           'ID Year': 2015,
           'Population': 2978204,
           'Slug State': 'arkansas',
           'State': 'Arkansas',
           'Year': '2015'},
          {'ID State': '04000US46',
           'ID Year': 2015,
           'Population': 858469,
           'Slug State': 'south-dakota',
           'State': 'South Dakota',
           'Year': '2015'},
          {'ID State': '04000US35',
           'ID Year': 2014,
           'Population': 2085572,
           'Slug State': 'new-mexico',
           'State': 'New Mexico',
           'Year': '2014'},
          {'ID State': '04000US46',
           'ID Year': 2014,
           'Population': 853175,
           'Slug State': 'south-dakota',
           'State': 'South Dakota',
           'Year': '2014'},
          {'ID State': '04000US45',
           'ID Year': 2014,
           'Population': 4832482,
           'Slug State': 'south-carolina',
           'State': 'South Carolina',
           'Year': '2014'},
          {'ID State': '04000US47',
           'ID Year': 2014,
           'Population': 6549352,
           'Slug State': 'tennessee',
           'State': 'Tennessee',
           'Year': '2014'},
          {'ID State': '04000US11',
           'ID Year': 2014,
           'Population': 658893,
           'Slug State': 'district-of-columbia',
           'State': 'District of Columbia',
           'Year': '2014'},
          {'ID State': '04000US44',
           'ID Year': 2014,
           'Population': 1055173,
           'Slug State': 'rhode-island',
           'State': 'Rhode Island',
           'Year': '2014'},
          {'ID State': '04000US12',
           'ID Year': 2014,
           'Population': 19893297,
           'Slug State': 'florida',
           'State': 'Florida',
           'Year': '2014'},
          {'ID State': '04000US09',
           'ID Year': 2014,
           'Population': 3596677,
           'Slug State': 'connecticut',
           'State': 'Connecticut',
           'Year': '2014'},
          {'ID State': '04000US48',
           'ID Year': 2014,
           'Population': 26956958,
           'Slug State': 'texas',
           'State': 'Texas',
           'Year': '2014'},
          {'ID State': '04000US42',
           'ID Year': 2014,
           'Population': 12787209,
           'Slug State': 'pennsylvania',
           'State': 'Pennsylvania',
           'Year': '2014'},
          {'ID State': '04000US41',
           'ID Year': 2014,
           'Population': 3970239,
           'Slug State': 'oregon',
           'State': 'Oregon',
           'Year': '2014'},
          {'ID State': '04000US13',
           'ID Year': 2014,
           'Population': 10097343,
           'Slug State': 'georgia',
           'State': 'Georgia',
           'Year': '2014'},
          {'ID State': '04000US25',
           'ID Year': 2014,
           'Population': 6745408,
           'Slug State': 'massachusetts',
           'State': 'Massachusetts',
           'Year': '2014'},
          {'ID State': '04000US49',
           'ID Year': 2014,
           'Population': 2942902,
           'Slug State': 'utah',
           'State': 'Utah',
           'Year': '2014'},
          {'ID State': '04000US40',
           'ID Year': 2014,
           'Population': 3878051,
           'Slug State': 'oklahoma',
           'State': 'Oklahoma',
           'Year': '2014'},
          {'ID State': '04000US15',
           'ID Year': 2014,
           'Population': 1419561,
           'Slug State': 'hawaii',
           'State': 'Hawaii',
           'Year': '2014'},
          {'ID State': '04000US08',
           'ID Year': 2014,
           'Population': 5355866,
           'Slug State': 'colorado',
           'State': 'Colorado',
           'Year': '2014'},
          {'ID State': '04000US39',
           'ID Year': 2014,
           'Population': 11594163,
           'Slug State': 'ohio',
           'State': 'Ohio',
           'Year': '2014'},
          {'ID State': '04000US50',
           'ID Year': 2014,
           'Population': 626562,
           'Slug State': 'vermont',
           'State': 'Vermont',
           'Year': '2014'},
          {'ID State': '04000US38',
           'ID Year': 2014,
           'Population': 739482,
           'Slug State': 'north-dakota',
           'State': 'North Dakota',
           'Year': '2014'},
          {'ID State': '04000US16',
           'ID Year': 2014,
           'Population': 1634464,
           'Slug State': 'idaho',
           'State': 'Idaho',
           'Year': '2014'},
          {'ID State': '04000US37',
           'ID Year': 2014,
           'Population': 9943964,
           'Slug State': 'north-carolina',
           'State': 'North Carolina',
           'Year': '2014'},
          {'ID State': '04000US06',
           'ID Year': 2014,
           'Population': 38802500,
           'Slug State': 'california',
           'State': 'California',
           'Year': '2014'},
          {'ID State': '04000US51',
           'ID Year': 2014,
           'Population': 8326289,
           'Slug State': 'virginia',
           'State': 'Virginia',
           'Year': '2014'},
          {'ID State': '04000US17',
           'ID Year': 2014,
           'Population': 12880580,
           'Slug State': 'illinois',
           'State': 'Illinois',
           'Year': '2014'},
          {'ID State': '04000US36',
           'ID Year': 2014,
           'Population': 19746227,
           'Slug State': 'new-york',
           'State': 'New York',
           'Year': '2014'},
          {'ID State': '04000US10',
           'ID Year': 2014,
           'Population': 935614,
           'Slug State': 'delaware',
           'State': 'Delaware',
           'Year': '2014'},
          {'ID State': '04000US18',
           'ID Year': 2014,
           'Population': 6596855,
           'Slug State': 'indiana',
           'State': 'Indiana',
           'Year': '2014'},
          {'ID State': '04000US53',
           'ID Year': 2014,
           'Population': 7061530,
           'Slug State': 'washington',
           'State': 'Washington',
           'Year': '2014'},
          {'ID State': '04000US34',
           'ID Year': 2014,
           'Population': 8938175,
           'Slug State': 'new-jersey',
           'State': 'New Jersey',
           'Year': '2014'},
          {'ID State': '04000US19',
           'ID Year': 2014,
           'Population': 3107126,
           'Slug State': 'iowa',
           'State': 'Iowa',
           'Year': '2014'},
          {'ID State': '04000US05',
           'ID Year': 2014,
           'Population': 2966369,
           'Slug State': 'arkansas',
           'State': 'Arkansas',
           'Year': '2014'},
          {'ID State': '04000US33',
           'ID Year': 2014,
           'Population': 1326813,
           'Slug State': 'new-hampshire',
           'State': 'New Hampshire',
           'Year': '2014'},
          {'ID State': '04000US54',
           'ID Year': 2014,
           'Population': 1850326,
           'Slug State': 'west-virginia',
           'State': 'West Virginia',
           'Year': '2014'},
          {'ID State': '04000US32',
           'ID Year': 2014,
           'Population': 2839099,
           'Slug State': 'nevada',
           'State': 'Nevada',
           'Year': '2014'},
          {'ID State': '04000US20',
           'ID Year': 2014,
           'Population': 2904021,
           'Slug State': 'kansas',
           'State': 'Kansas',
           'Year': '2014'},
          {'ID State': '04000US31',
           'ID Year': 2014,
           'Population': 1881503,
           'Slug State': 'nebraska',
           'State': 'Nebraska',
           'Year': '2014'},
          {'ID State': '04000US04',
           'ID Year': 2014,
           'Population': 6731484,
           'Slug State': 'arizona',
           'State': 'Arizona',
           'Year': '2014'},
          {'ID State': '04000US55',
           'ID Year': 2014,
           'Population': 5757564,
           'Slug State': 'wisconsin',
           'State': 'Wisconsin',
           'Year': '2014'},
          {'ID State': '04000US21',
           'ID Year': 2014,
           'Population': 4413457,
           'Slug State': 'kentucky',
           'State': 'Kentucky',
           'Year': '2014'},
          {'ID State': '04000US30',
           'ID Year': 2014,
           'Population': 1023579,
           'Slug State': 'montana',
           'State': 'Montana',
           'Year': '2014'},
          {'ID State': '04000US29',
           'ID Year': 2014,
           'Population': 6063589,
           'Slug State': 'missouri',
           'State': 'Missouri',
           'Year': '2014'},
          {'ID State': '04000US22',
           'ID Year': 2014,
           'Population': 4649676,
           'Slug State': 'louisiana',
           'State': 'Louisiana',
           'Year': '2014'},
          {'ID State': '04000US56',
           'ID Year': 2014,
           'Population': 584153,
           'Slug State': 'wyoming',
           'State': 'Wyoming',
           'Year': '2014'},
          {'ID State': '04000US28',
           'ID Year': 2014,
           'Population': 2994079,

           'ID Year': 2013,
           'Population': 1404054,
           'Slug State': 'hawaii',
           'State': 'Hawaii',
           'Year': '2013'},
          {'ID State': '04000US08',
           'ID Year': 2013,
           'Population': 5268367,
           'Slug State': 'colorado',
           'State': 'Colorado',
           'Year': '2013'},
          {'ID State': '04000US38',
           'ID Year': 2013,
           'Population': 723393,
           'Slug State': 'north-dakota',
           'State': 'North Dakota',
           'Year': '2013'},
          {'ID State': '04000US02',
           'ID Year': 2013,
           'Population': 735132,
           'Slug State': 'alaska',
           'State': 'Alaska',
           'Year': '2013'},
          {'ID State': '04000US55',
           'ID Year': 2013,
           'Population': 5742713,
           'Slug State': 'wisconsin',
           'State': 'Wisconsin',
           'Year': '2013'},
          {'ID State': '04000US46',
           'ID Year': 2013,
           'Population': 844877,
           'Slug State': 'south-dakota',
           'State': 'South Dakota',
           'Year': '2013'},
          {'ID State': '04000US28',
           'ID Year': 2013,
           'Population': 2991207,
           'Slug State': 'mississippi',
           'State': 'Mississippi',
           'Year': '2013'},
          {'ID State': '04000US24',
           'ID Year': 2013,
           'Population': 5928814,
           'Slug State': 'maryland',
           'State': 'Maryland',
           'Year': '2013'},
          {'ID State': '04000US33',
           'ID Year': 2013,
           'Population': 1323459,
           'Slug State': 'new-hampshire',
           'State': 'New Hampshire',
           'Year': '2013'},
          {'ID State': '04000US01',
           'ID Year': 2013,
           'Population': 4833722,
           'Slug State': 'alabama',
           'State': 'Alabama',
           'Year': '2013'},
          {'ID State': '04000US56',
           'ID Year': 2013,
           'Population': 582658,
           'Slug State': 'wyoming',
           'State': 'Wyoming',
           'Year': '2013'},
          {'ID State': '04000US39',
           'ID Year': 2013,
           'Population': 11570808,
           'Slug State': 'ohio',
           'State': 'Ohio',
           'Year': '2013'},
          {'ID State': '04000US47',
           'ID Year': 2013,
           'Population': 6495978,
           'Slug State': 'tennessee',
           'State': 'Tennessee',
           'Year': '2013'},
          {'ID State': '04000US18',
           'ID Year': 2013,
           'Population': 6570902,
           'Slug State': 'indiana',
           'State': 'Indiana',
           'Year': '2013'},
          {'ID State': '04000US21',
           'ID Year': 2013,
           'Population': 4395295,
           'Slug State': 'kentucky',
           'State': 'Kentucky',
           'Year': '2013'},
          {'ID State': '04000US11',
           'ID Year': 2013,
           'Population': 646449,
           'Slug State': 'district-of-columbia',
           'State': 'District of Columbia',
           'Year': '2013'},
          {'ID State': '04000US72',
           'ID Year': 2013,
           'Population': 3615086,
           'Slug State': 'puerto-rico',
           'State': 'Puerto Rico',
           'Year': '2013'},
          {'ID State': '04000US29',
           'ID Year': 2013,
           'Population': 6044171,
           'Slug State': 'missouri',
           'State': 'Missouri',
           'Year': '2013'},
          {'ID State': '04000US34',
           'ID Year': 2013,
           'Population': 8899339,
           'Slug State': 'new-jersey',
           'State': 'New Jersey',
           'Year': '2013'},
          {'ID State': '04000US48',
           'ID Year': 2013,
           'Population': 26448193,
           'Slug State': 'texas',
           'State': 'Texas',
           'Year': '2013'},
          {'ID State': '04000US40',
           'ID Year': 2013,
           'Population': 3850568,
           'Slug State': 'oklahoma',
           'State': 'Oklahoma',
           'Year': '2013'},
          {'ID State': '04000US30',
           'ID Year': 2013,
           'Population': 1015165,
           'Slug State': 'montana',
           'State': 'Montana',
           'Year': '2013'}],
 'source': [{'annotations': {'dataset_link': 'http://www.census.gov/programs-surveys/acs/',
                             'dataset_name': 'ACS 1-year Estimate',
                             'source_description': 'The American Community '
                                                   'Survey (ACS) is conducted '
                                                   'by the US Census and sent '
                                                   'to a portion of the '
                                                   'population every year.',
                             'source_name': 'Census Bureau',
                             'subtopic': 'Demographics',
                             'table_id': 'B01003',
                             'topic': 'Diversity'},
             'measures': ['Population'],
             'name': 'acs_yg_total_population_1',
             'substitutions': []}]}

In [66]:
file_name = "Resources/population.json"
import pandas as pd
df = pd.read_json(file_name)

In [117]:
from pandas.io.json import json_normalize
df=json_normalize(data['data'])

In [118]:
df.head()

    ID State        State  ID Year  Year  Population   Slug State
0  04000US39         Ohio     2018  2018    11689442         ohio
1  04000US72  Puerto Rico     2018  2018     3195153  puerto-rico
2  04000US01      Alabama     2018  2018     4887871      alabama
3  04000US55    Wisconsin     2018  2018     5813568    wisconsin
4  04000US02       Alaska     2018  2018      737438       alaska

In [119]:
df=df.rename(columns={"ID State": "id_state", "State": "state",
                   "ID Year":"id_year","Year":"year",
                   "Population":"population","Slug State":"slug_state"})

In [120]:
engine = create_engine('postgres+psycopg2://postgres:password@localhost:5432/project2_db')

In [121]:
df.to_sql(name='population_table',con=engine,if_exists='replace',index=True)